#!/bin/bash

# Environment Variables - private template
#
# DO NOT EDIT THIS FILE!  Make a copy of this file named 'env-private.sh' and
# make your changes there. Limit your changes to the variables provided by the
# template, unless you know what you're doing.

# your Ethereum wallet address
suggested_fee_recipient=''

# the ethereum network to use (holesky or mainnet)
ethereum_network='mainnet'

# the local IP address of your router
router_ip_address='192.168.1.1'

# node server values used during initial setup
node_server_ip_address='192.168.1.25'
node_server_ssh_port=55522 # TCP
node_server_timezone='America/Los_Angeles'
node_server_hostname='eth-node-mainnet'
node_server_username='coejoder'
node_server_secondary_storage='/mnt/secondary'

# external geth ports
geth_port=30303           # TCP
geth_discovery_port=30303 # UDP
geth_datadir_secondary="$node_server_secondary_storage/geth"
geth_datadir_secondary_ancient="$geth_datadir_secondary/chaindata/ancient"

# external prysm ports
prysm_beacon_p2p_tcp_port=13000  # TCP
prysm_beacon_p2p_quic_port=13000 # UDP
prysm_beacon_p2p_udp_port=12000  # UDP

# prysm max external connections
prysm_beacon_p2p_max_peers=30

# the hard-coded behavior is to use checkpoint-sync only on 'holesky' testnet 
# these variables are ignored unless `ethereum_network` is set to 'holesky'
prysm_beacon_checkpoint_sync_url='https://holesky.beaconstate.info'
prysm_beacon_genesis_beacon_api_url='https://holesky.beaconstate.info'
