#!/bin/bash

# Environment Variables - Override Template
#
# DO NOT EDIT THIS FILE!
#
# Make a copy of this file named 'env-private.sh' and make your changes there.
# Limit your changes to the variables provided by the template, unless you 
# know what you're doing.

suggested_fee_recipient=''

ethereum_network='mainnet'

router_ip_address='192.168.1.1'

node_server_ip_address='192.168.1.25'
node_server_ssh_port=55522 # TCP
node_server_timezone='America/Los_Angeles'
node_server_hostname='eth-node-mainnet'
node_server_username='coejoder'
node_server_secondary_storage='/mnt/secondary'

geth_port=30303           # TCP
geth_discovery_port=30303 # UDP

prysm_beacon_p2p_tcp_port=13000  # TCP
prysm_beacon_p2p_quic_port=13000 # UDP
prysm_beacon_p2p_udp_port=12000  # UDP
prysm_beacon_p2p_max_peers=30

# the hard-coded behavior is to use checkpoint-sync only on 'holesky' testnet 
prysm_beacon_checkpoint_sync_url='https://holesky.beaconstate.info'
prysm_beacon_genesis_beacon_api_url='https://holesky.beaconstate.info'
