#!/bin/bash

# Environment Variables - Base
#
# DO NOT EDIT THIS FILE!
# Run `setup-env.sh` to generate an editable `env.sh` file.

# the Ethereum network to use (hoodi or mainnet)
ethereum_network='hoodi'

# node server values used during initial setup
node_server_ssh_port=55522 # TCP
node_server_timezone='America/Los_Angeles'
node_server_hostname='eth-node-mainnet'
node_server_username='coejoder'
node_server_secondary_storage='/mnt/secondary'

# the location of the JWT secret shared between EL and CL
eth_jwt_file='/usr/local/secrets/eth_jwt.hex'

# the location of the 'DATA' drive mount point
client_pc_usb_data_drive="/media/$USER/DATA"

# the location of the 'DATA' distribution
usb_dist_dir="$client_pc_usb_data_drive/$dist_dirname"

# the location of the `bls-to-execution-changes` signed messages
usb_bls_to_execution_changes_dir="$usb_dist_dir/bls_to_execution_changes"

# the location of the exported validator statuses
validator_statuses_json="$usb_dist_dir/validator_statuses.json"

# geth values
geth_user='goeth'
geth_group='goeth'
geth_bin='geth'
geth_datadir='/var/lib/goeth'
geth_unit_file='/etc/systemd/system/eth1.service'
geth_port=30303           # TCP
geth_discovery_port=30303 # UDP
geth_datadir_secondary="$node_server_secondary_storage/geth"
geth_datadir_secondary_ancient="$geth_datadir_secondary/chaindata/ancient"

# prysm-beacon values
prysm_beacon_user='prysmbeacon'
prysm_beacon_group='prysmbeacon'
prysm_beacon_bin='/usr/local/bin/beacon-chain'
prysm_beacon_datadir='/var/lib/prysm/beacon'
prysm_beacon_unit_file='/etc/systemd/system/eth2-beacon.service'
prysm_beacon_http_port=3500      # TCP
prysm_beacon_p2p_tcp_port=13000  # TCP
prysm_beacon_p2p_quic_port=13000 # UDP
prysm_beacon_p2p_udp_port=12000  # UDP
prysm_beacon_p2p_max_peers=30

# the hard-coded behavior is to use checkpoint-sync only on 'hoodi' testnet
# these variables are ignored unless `ethereum_network` is set to 'hoodi'
prysm_beacon_checkpoint_sync_url='https://hoodi.beaconstate.info'
prysm_beacon_genesis_beacon_api_url='https://hoodi.beaconstate.info'

# prysm-validator values
prysm_validator_user='prysmvalidator'
prysm_validator_group='prysmvalidator'
prysm_validator_bin='/usr/local/bin/validator'
prysm_validator_datadir='/var/lib/prysm/validator'
prysm_validator_keys_dir='/var/lib/prysm/validator/validator_keys'
prysm_validator_wallet_dir='/var/lib/prysm/validator/prysm-wallet-v2'
prysm_validator_wallet_password_file='/var/lib/prysm/validator/wallet-password.txt'
prysm_validator_unit_file='/etc/systemd/system/eth2-validator.service'
prysm_validator_beacon_rest_api_endpoint="http://127.0.0.1:$prysm_beacon_http_port"

# prysmctl values
prysmctl_user='prysmctl'
prysmctl_group='prysmctl'
prysmctl_bin='/usr/local/bin/prysmctl'
prysmctl_datadir='/var/lib/prysm/prysmctl'

# EthStaker Deposit CLI values
ethstaker_deposit_cli_version='v1.2.0'
ethstaker_deposit_cli_sha256_checksum='d17758a9a2dfd2f657a30cef8f5f8f16c95cc49e63e81e19b9fa2ac73aadd257'
ethstaker_deposit_cli_basename='ethstaker_deposit-cli-18b7608-linux-amd64.tar.gz'
ethstaker_deposit_cli_basename_sha256="${ethstaker_deposit_cli_basename}.sha256"
ethstaker_deposit_cli_url="https://github.com/eth-educators/ethstaker-deposit-cli/releases/download/$ethstaker_deposit_cli_version/$ethstaker_deposit_cli_basename"
ethstaker_deposit_cli_sha256_url="https://github.com/eth-educators/ethstaker-deposit-cli/releases/download/$ethstaker_deposit_cli_version/$ethstaker_deposit_cli_basename_sha256"

# Portable `jq` values
jq_version='jq-1.7.1'
jq_bin='jq-linux-amd64'
jq_bin_sha256='jq-linux-amd64.sha256'
jq_bin_dist="$usb_dist_dir/$jq_bin"
jq_bin_sha256_dist="$usb_dist_dir/$jq_bin_sha256"
